package com.vlohachov.moviespot.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006E08)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF97F986)
val md_theme_light_onPrimaryContainer = Color(0xFF002201)
val md_theme_light_secondary = Color(0xFF53634E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E8CD)
val md_theme_light_onSecondaryContainer = Color(0xFF121F0E)
val md_theme_light_tertiary = Color(0xFF386569)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBEF)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF6)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_surface = Color(0xFFFCFDF6)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D8)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inversePrimary = Color(0xFF7CDC6D)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E08)

val md_theme_dark_primary = Color(0xFF7CDC6D)
val md_theme_dark_onPrimary = Color(0xFF003A02)
val md_theme_dark_primaryContainer = Color(0xFF005304)
val md_theme_dark_onPrimaryContainer = Color(0xFF97F986)
val md_theme_dark_secondary = Color(0xFFBBCBB2)
val md_theme_dark_onSecondary = Color(0xFF263422)
val md_theme_dark_secondaryContainer = Color(0xFF3C4B37)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E8CD)
val md_theme_dark_tertiary = Color(0xFFA0CFD2)
val md_theme_dark_onTertiary = Color(0xFF00373A)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4D51)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCEBEF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C18)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BC)
val md_theme_dark_outline = Color(0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF006E08)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7CDC6D)


val seed = Color(0xFF006F08)
