package com.vlohachov.moviespot.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFF006E08)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFF97F986)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF002201)
val md_theme_light_secondary = Color(color = 0xFF53634E)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFFD7E8CD)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF121F0E)
val md_theme_light_tertiary = Color(color = 0xFF386569)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFFBCEBEF)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF002022)
val md_theme_light_error = Color(color = 0xFFBA1A1A)
val md_theme_light_errorContainer = Color(color = 0xFFFFDAD6)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(color = 0xFF410002)
val md_theme_light_background = Color(color = 0xFFFCFDF6)
val md_theme_light_onBackground = Color(color = 0xFF1A1C18)
val md_theme_light_surface = Color(color = 0xFFFCFDF6)
val md_theme_light_onSurface = Color(color = 0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(color = 0xFFDFE4D8)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF43483F)
val md_theme_light_outline = Color(color = 0xFF73796E)
val md_theme_light_inverseOnSurface = Color(color = 0xFFF1F1EB)
val md_theme_light_inverseSurface = Color(color = 0xFF2F312D)
val md_theme_light_inversePrimary = Color(color = 0xFF7CDC6D)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFF006E08)

val md_theme_dark_primary = Color(color = 0xFF7CDC6D)
val md_theme_dark_onPrimary = Color(color = 0xFF003A02)
val md_theme_dark_primaryContainer = Color(color = 0xFF005304)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFF97F986)
val md_theme_dark_secondary = Color(color = 0xFFBBCBB2)
val md_theme_dark_onSecondary = Color(color = 0xFF263422)
val md_theme_dark_secondaryContainer = Color(color = 0xFF3C4B37)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFFD7E8CD)
val md_theme_dark_tertiary = Color(color = 0xFFA0CFD2)
val md_theme_dark_onTertiary = Color(color = 0xFF00373A)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF1E4D51)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFFBCEBEF)
val md_theme_dark_error = Color(color = 0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(color = 0xFF93000A)
val md_theme_dark_onError = Color(color = 0xFF690005)
val md_theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_background = Color(color = 0xFF1A1C18)
val md_theme_dark_onBackground = Color(color = 0xFFE2E3DD)
val md_theme_dark_surface = Color(color = 0xFF1A1C18)
val md_theme_dark_onSurface = Color(color = 0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(color = 0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFC3C8BC)
val md_theme_dark_outline = Color(color = 0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(color = 0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(color = 0xFF006E08)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFF7CDC6D)


val seed = Color(color = 0xFF006F08)
